//import Foundation
//
//private final class BundleFinder: NSObject {}
//extension Bundle {
//  static let vodQa = Bundle(for: BundleFinder.self)
//}


import Foundation

/// Wraps `Bundle.module` (which SwiftPM makes `internal`) in a `public` property.
/// Other modules (your app, test targets, etc.) can call `Bundle.mySwiftUIPackage`
/// to access resources bundled in `Resources/`.
public extension Bundle {
    static var mySwiftUIPackage: Bundle {
        // `Bundle.module` is auto-generated by SwiftPM for any target that lists `resources: [...]`
        return .module
    }
}
